### ISSUE TITLE
which key is bound to card in

### ISSUE THREAD

**Issue by Sonic1paRadise** [djhackersdev/bemanitools#265]
i cant insert card.
it was + on spice
and i dont know what key it is on bemani tools.
also, the texture issue is NOT fixed
![image](https://github.com/djhackersdev/bemanitools/assets/51707249/15651893-3012-4f47-b004-c390a2a3f64e)
(you can see the diagonal crap)

**Comment by Sonic1paRadise** [comment]
also
i cannot type anything in Lincle(CONTROLS BOUND)

**Comment by Sonic1paRadise** [comment]
fixed most of these, but the issue with the keypad is still active.
while it is detected in config
it is not detected in game(10key check does not respond)
also
the resort thing looks more like a wasteland on my pc(just water and no skybox)

**Comment by icex2** [comment]
> it is not detected in game(10key check does not respond)

Do you have num lock on or off according to how you assigned it in the config tool? How are you checking the keypad in the game? I suggest you go to the test menu and do it there as you can easily detect if you mixed up the player sides by accident.

> the resort thing looks more like a wasteland on my pc(just water and no skybox)

Do you have screenshots? Might be a(nother) gfx issue that wasn't fixed thus far.

**Comment by Sonic1paRadise** [comment]
> Do you have num lock on or off according to how you assigned it in the config tool? How are you checking the keypad in the game? I suggest you go to the test menu and do it there as you can easily detect if you mixed up the player sides by accident.

as i said before, the 10key check in the test menu does not detect anyting.

> Do you have screenshots? Might be a(nother) gfx issue that wasn't fixed thus far.

LADIES AND GENTLEMEN, WE PRESENT YOU THE NEWEST INSTALLMENT OF IIDX SERIES:
IIDX 18 - RESORT WASTELAND(i forgot to set diagonal tearing fix back on sorry)
![image](https://github.com/djhackersdev/bemanitools/assets/51707249/3f1a5037-a4e4-49b6-8181-cd21b1689a1d)
as you can clearly see,  its only the clouds and the water with the rainbow

**Comment by icex2** [comment]
> > Do you have num lock on or off according to how you assigned it in the config tool? How are you checking the keypad in the game? I suggest you go to the test menu and do it there as you can easily detect if you mixed up the player sides by accident.
> 
> as i said before, the 10key check in the test menu does not detect anyting.

Sorry, didn't get that part last time. That's odd. We would need more information to debug this further, e.g. log output, your keyboard, screenshot of the network config tool page etc. The more the better as we are currently just playing a guessing game.

> > Do you have screenshots? Might be a(nother) gfx issue that wasn't fixed thus far.
> 
> LADIES AND GENTLEMEN, WE PRESENT YOU THE NEWEST INSTALLMENT OF IIDX SERIES: IIDX 18 - RESORT WASTELAND(i forgot to set diagonal tearing fix back on sorry) ![image](https://user-images.githubusercontent.com/51707249/282787941-3f1a5037-a4e4-49b6-8181-cd21b1689a1d.png) as you can clearly see, its only the clouds and the water with the rainbow

That's new to me at least. Might be another or new issue with whatever system and hardware you are using. Again, more information is always helpful, so your PC and OS specs would be good to know.

**Comment by Sonic1paRadise** [comment]
Ok bud, wait a couple of hours. its night now in my timezone.

Tue, 14 Nov 2023 ., 20:51 icex2 ***@***.***>:

**Comment by Sonic1paRadise** [comment]
for some reason, logfile was not created
but i have this picture
![image](https://github.com/djhackersdev/bemanitools/assets/51707249/04dc6c4f-ab1c-4fae-9cf2-8e0c80a6e022)
regarding system:
Intel i3-2120(this is more powerful than the og cab)
16G ram
NViDiA GT 1030

**Comment by Sonic1paRadise** [comment]
for some reason, i can eat tomatoes now
